-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 17:37:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema puntoReciclaje
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema puntoReciclaje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puntoReciclaje` DEFAULT CHARACTER SET utf8 ;
USE `puntoReciclaje` ;

-- -----------------------------------------------------
-- Table `puntoReciclaje`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoReciclaje`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `rol` INT NOT NULL,
  `estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idCuenta`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puntoReciclaje`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoReciclaje`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `idCuenta` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Cuenta1_idx` (`idCuenta` ASC) ,
  CONSTRAINT `fk_Usuario_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `puntoReciclaje`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puntoReciclaje`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoReciclaje`.`Colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_residuo` VARCHAR(45) NOT NULL,
  `servicio_ofrecido` VARCHAR(100) NOT NULL,
  `idCuenta` INT NOT NULL,
  PRIMARY KEY (`idColaborador`),
  INDEX `fk_Colaborador_Cuenta1_idx` (`idCuenta` ASC) ,
  CONSTRAINT `fk_Colaborador_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `puntoReciclaje`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
